name: comp_genomics
channels:
 - pytorch
 - defaults
dependencies:
 - python=3.9.7
 - numpy=1.21.2
 - pandas=1.3.5
 - matplotlib=3.5.0
 - seaborn=0.11.2
 - jupyterlab=3.2.9
 - pytorch=1.10.2
 - scikit-learn=1.0.2
